# mysql/pvc.yaml
apiVersion: v1 
kind: PersistentVolumeClaim
 metadata:
   name: mysql-storage # MARK Z
   namespace: wordpress-tutorial # Must match with namespace.
 spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 10Gi